JPK_django/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from JPK_app.views import ConvertXLMView, JPKFileCreate, JPKFileShow, JPKTableShow, JPKFileList, JPKFileEdit, JPKTableEdit, JPKTagEdit

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^conversion_db/$', ConvertXLMView.as_view(), name='conversion_db'),
    url(r'^file_create/$', JPKFileCreate.as_view(), name='file_create'),
    url(r'^file_show/(?P<pk>(\d)+)/$', JPKFileShow.as_view(), name='file_show'),
    url(r'^table_show/(?P<pk>(\d)+)/$', JPKTableShow.as_view(), name='table_show'),
    url(r'^file_list/$',JPKFileList.as_view(), name='file_list'),
    url(r'^file_edit/(?P<pk>(\d)+)/$', JPKFileEdit.as_view(), name='file_edit'),
    url(r'^table_edit/(?P<pk>(\d)+)/$', JPKTableEdit.as_view(), name='table_edit'),
    url(r'^tag_edit/(?P<pk>(\d)+)/$', JPKTagEdit.as_view(), name='tag_edit'),
    url(r'^login/$', auth_views.login, {'template_name': 'JPK_app/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JPK_app/models.py
from django.db import models
from django.contrib.auth.models import User


class LoadedFile(models.Model):
    path = models.FileField()
    date_creation = models.DateTimeField(auto_now_add=True)

    @property
    def name(self):
        return '{}'.format(self.path.name)
    
    @property
    def new_name(self):
        return '{}'.format(self.path.name[6:-4])



class JPKFile(models.Model):
    """Tags structure - file"""
    name = models.CharField(max_length=125, verbose_name='nazwa pliku')
    raw_ns = models.CharField(max_length=125, verbose_name='namespace')

    def __str__(self):
        return self.name

    @property
    def ns(self):
        return '{{{}}}'.format(self.raw_ns)

class JPKTable(models.Model):
    """Tags structure - table"""
    name = models.CharField(max_length=64, verbose_name='tabela')
    file = models.ForeignKey(JPKFile, on_delete=models.CASCADE, verbose_name='plik', related_name='tables')

    def __str__(self):
        return '{}: {}'.format(self.file, self.name)


TYPES = (
    ("str", "znakowy"),
    ("date", "data"),
    ("value", "kwotowy"),
    ("num", "liczbowy"),
)

class JPKTag(models.Model):
    """Tags structure - tag"""
    name = models.CharField(max_length=64, verbose_name='tag')
    type = models.CharField(choices=TYPES, default="str", max_length=16, verbose_name='typ')
    table = models.ForeignKey(JPKTable, on_delete=models.CASCADE, verbose_name='tabela', related_name='tags')

JPK_app/forms.py
from django import forms
from .models import LoadedFile, JPKFile, JPKTag, JPKTable


class LoadedFileForm(forms.ModelForm):
    class Meta:
        model = LoadedFile
        fields = ['path', ]


class JPKFileForm(forms.ModelForm):
    class Meta:
        model = JPKFile
        fields = '__all__'


class JPKTableForm(forms.ModelForm):
    class Meta:
        model = JPKTable
        fields = ['name', ]


class JPKTagForm(forms.ModelForm):
    class Meta:
        model = JPKTag
        fields = ['name', 'type',]

JPK_app/views.py
import os
import sys
import shutil

from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponseBadRequest, HttpResponse, Http404
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import LoadedFile, JPKFile, JPKTag, JPKTable
from .forms import LoadedFileForm, JPKFileForm, JPKTableForm, JPKTagForm

from .process_xml_data import get_ns
from .prepare_tags_scheme import prepare_tags_scheme
from .build_excel_file import worksheets_generate
from .handle_zip_archive import handle_zip_file

import xlsxwriter

import zipfile

# Create your views here.

class ConvertXLMView(View):

    # display upload form
    def get(self, request):

        form = LoadedFileForm()
        ctx = {'form': form}

        return render(request, 'JPK_app/conversion.html', ctx)


    # handle uploaded file
    def post(self, request):

        form = LoadedFileForm(request.POST, request.FILES)

        if form.is_valid():

            # process loaded file by saving its path as a db row
            file = LoadedFile.objects.create(**form.cleaned_data)
            file_path = file.path.url[1::]
            file_name = file.name[:-4]


            # if loaded file is a zip, extract xml file from the archive and rewrite file_path and file_name variables
            if file.name.endswith(('.zip', '.ZIP', )):
                try:
                    unzipped_file= handle_zip_file(file)
                    file_path = unzipped_file
                    file_name = unzipped_file[6:-4]

                except zipfile.BadZipfile as e:
                    print(e)
                except zipfile.LargeZipFile as e:
                    print(e)

            # define type of xml file by getting its namespace
            ns = get_ns(file_path)

            # handle empty ns
            if not ns:
                return HttpResponse("Plik nie zawiera tagu definiującego go jako plik JPK_VAT lub JPK_KR zgodnie z instrukcją MF")

            # get tags of xml file based on its namespace
            obj = prepare_tags_scheme(ns)

            # define response as a xlsx file to download
            response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            response['Content-Disposition'] = "attachment; filename={}.xlsx".format(file_name)

            # basic excel settings
            workbook = xlsxwriter.Workbook(response, {'in_memory': True})

            # create worksheets where obj provides table and column names and file yields data to fill them
            worksheets_generate(obj, workbook, file_path, ns)

            workbook.close()

            # remove loaded file from db
            file.delete()

            # delete media folder with its content
            try:
                shutil.rmtree(settings.MEDIA_ROOT)
            except OSError as e:
                print("Error: %s - %s." % (e.filename, e.strerror))

            return response

        form = LoadedFileForm()
        ctx = {'form': form,}
        return render(request, 'JPK_app/conversion.html', ctx)


class JPKFileCreate(LoginRequiredMixin, View):
    """create file"""
    def get(self, request):
        form = JPKFileForm()
        ctx = {
            'form': form,
        }
        return render(request, 'JPK_app/jpkfile_form.html', ctx)

    def post(self, request):
        form = JPKFileForm(request.POST)
        if form.is_valid():
            file = form.save()
            return redirect('file_show', pk=file.pk)
        ctx = {
            'form': form,
        }
        return render(request, 'JPK_app/jpkfile_form.html', ctx)


class JPKFileShow(LoginRequiredMixin, View):
    """create tables in a file"""
    def get(self, request, pk):
        file = JPKFile.objects.get(pk=pk)
        form = JPKTableForm()
        tables = file.tables.all()
        ctx = {
            'file': file,
            'form': form,
            'tables': tables,
        }
        return render(request, 'JPK_app/jpkfile_show.html', ctx)

    def post(self, request, pk):
        file = JPKFile.objects.get(pk=pk)
        form = JPKTableForm(request.POST)

        if form.is_valid():
            table = JPKTable.objects.create(file=file, **form.cleaned_data)
            return redirect('table_show', pk=table.pk)

        tables = file.tables.all()
        ctx = {
            'file': file,
            'form': form,
            'tables': tables,
        }
        return render(request, 'JPK_app/jpkfile_show.html', ctx)


class JPKTableShow(LoginRequiredMixin, View):
    """create tags in a table"""
    def get(self, request, pk):
        table = JPKTable.objects.get(pk=pk)
        file = JPKFile.objects.get(pk=table.file.pk)
        tags = table.tags.all()
        form = JPKTagForm()
        ctx = {
            'table': table,
            'file': file,
            'form': form,
            'tags': tags,
        }
        return render(request, 'JPK_app/jpktable_show.html', ctx)

    def post(self, request, pk):
        table = JPKTable.objects.get(pk=pk)
        file = JPKFile.objects.get(pk=table.file.pk)
        form = JPKTagForm(request.POST)

        if form.is_valid():
            JPKTag.objects.create(table=table, **form.cleaned_data)
            form = JPKTagForm()

        tags = table.tags.all()
        ctx = {
            'table': table,
            'file': file,
            'form': form,
            'tags': tags,
        }
        return render(request, 'JPK_app/jpktable_show.html', ctx)


class JPKFileList(LoginRequiredMixin, View):
    """list all jpk files"""
    def get(self, request):
        files = JPKFile.objects.all()
        ctx = {
            'files': files,
        }
        return render(request, 'JPK_app/jpkfile_list.html', ctx)


class JPKFileEdit(View):
    """edit jpk file"""
    def get(self, request, pk):
        file = JPKFile.objects.get(pk=pk)
        form = JPKFileForm(instance=file)

        ctx = {
            'file': file,
            'form': form,
        }

        return render(request, 'JPK_app/jpkfile_edit.html', ctx)

    def post(self, request, pk):
        file = JPKFile.objects.get(pk=pk)
        form = JPKFileForm(request.POST, instance=file)

        if form.is_valid():
            form.save()
            return redirect('file_show', pk=pk)

        ctx = {
            'file': file,
            'form': form,
        }

        return render(request, 'JPK_app/jpkfile_edit.html', ctx)


class JPKTableEdit(LoginRequiredMixin, View):
    """edit jpk table"""
    def get(self, request, pk):
        table = JPKTable.objects.get(pk=pk)
        form = JPKTableForm(instance=table)
        ctx = {
            'table': table,
            'form': form,
        }
        return render(request, 'JPK_app/jpktable_edit.html', ctx)

    def post(self, request, pk):
        table = JPKTable.objects.get(pk=pk)
        form = JPKTableForm(request.POST, instance=table)
        if form.is_valid():
            if request.POST['submit'] == 'zapisz':
                form.save()
            elif request.POST['submit'] == 'usuń':
                form.delete()
            return redirect('file_show', pk=table.file.pk)

        ctx = {
            'table': table,
            'form': form,
        }
        return render(request, 'JPK_app/jpktable_edit.html', ctx)


class JPKTagEdit(LoginRequiredMixin, View):
    """edit jpk tag"""
    def get(self, request, pk):
        tag = JPKTag.objects.get(pk=pk)
        form = JPKTagForm(instance=tag)
        ctx = {
            'tag': tag,
            'form': form,
        }
        return render(request, 'JPK_app/jpktag_edit.html', ctx)

    def post(self, request, pk):
        tag = JPKTag.objects.get(pk=pk)
        form = JPKTagForm(request.POST, instance=tag)
        if form.is_valid():
            if request.POST['submit'] == 'zapisz':
                form.save()
            elif request.POST['submit'] == 'usuń':
                form.delete()
            return redirect('file_show', pk=tag.table.file.pk)

        ctx = {
            'tag': tag,
            'form': form,
        }
        return render(request, 'JPK_app/jpktag_edit.html', ctx)

JPK_app/templates/JPK_app/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>XML_Konwerter</title>
    <link rel="stylesheet" href="{% static 'JPK_app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'JPK_app/css/style.css' %}">
</head>
<body>
    {% block nav %}
    <!-- Nav - start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="">xml konwerter</a>
            <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">

                    {% block link_management %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_list' %}">pliki</a>
                    </li>
                    {% endblock link_management %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">wyloguj</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Nav - stop -->
    {% endblock nav %}
    <section class="content">
        <div class="container">
            <div class="row">
                {% block content%}
                {% endblock content%}
            </div>
        </div>
    </section>

    <script src="{% static 'JPK_app/js/jquery-3.3.1.min.js'%}"></script>
    <!--<script src="{% static 'JPK_app/js/jquery-ui.min.js'%}"></script>-->
    <script src="{% static 'JPK_app/js/bootstrap.min.js'%}"></script>
</body>
</html>

JPK_app/templates/JPK_app/conversion.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block nav %}
{% endblock nav %}

{% block content %}
<div class="col-sm-6 offset-sm-3 default-div">
    <form action="" method="POST" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Upload" class="btn btn-info">
    </form>
</div>
{% endblock content %}

JPK_app/templates/JPK_app/jpkfile_edit.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-6 offset-sm-3 default-div">
    <h2 class="page-header">Plik</h2>
    <form action="" method="POST" class="form">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="submit" value="zapisz" class="btn btn-info">
    </form>
</div>
{% endblock content %}

JPK_app/templates/JPK_app/jpkfile_form.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h2 class="page-header">Plik JPK</h2>
<form action="" method="POST" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" name="submit" value="dodaj" class="btn btn-info">
</form>
{% endblock content %}

JPK_app/templates/JPK_app/jpkfile_list.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block link_management %}
{% endblock link_management %}

{% block content %}
<div class="col-sm-6 offset-sm-3 default-div">
    <h2 class="page-header">Pliki JPK</h2>
    <ul>
    {% for file in files %}
        <li><a href="{% url 'file_show' file.pk %}">{{ file.name }}</a></li>
    {% endfor %}
    </ul>
</div>
{% endblock content %}

JPK_app/templates/JPK_app/jpkfile_show.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-sm-6 offset-sm-3 default-div">
    <h2 class="page-header"><a href="{% url 'file_edit' file.pk %}">{{ file.name }}</a></h2>
    <p>namespace: {{ file.raw_ns }}</p>
</div>

<div class="col-sm-6 offset-sm-3 default-div">
    <form action="" method="POST" class="form jumbotron">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="submit" value="dodaj tabelę" class="btn btn-info">
    </form>
</div>

{% for table in tables %}
<div class="col-sm-6 offset-sm-3 default-div">
    <h4><a href="{% url 'table_show' table.pk %}">{{ table.name }}</a><a href="{% url 'table_edit' table.pk %}"> edytuj tabelę</a></h4>

    {% if table.tags.all %}
    <ul>
    {% for tag in table.tags.all %}
        <li><a href="{% url 'tag_edit' tag.pk %}">{{ tag.name }}, typ: {{ tag.get_type_display }}</a></li>
    {% endfor %}
    </ul>
    <hr>
    {% endif %}
</div>
{% endfor %}

{% endblock content %}

JPK_app/templates/JPK_app/jpktable_edit.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-6 offset-sm-3 default-div">
    <h2 class="page-header">Tabela</h2>
    <form action="" method="POST" class="form">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="submit" value="zapisz" class="btn btn-info">
        <input type="submit" name="submit" value="usuń" class="btn btn-danger">
    </form>
</div>
{% endblock content %}

JPK_app/templates/JPK_app/jpktable_show.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-sm-6 offset-sm-3 default-div">
    <h2 class="page-header">{{ table.name }}</h2>
    <hr>
</div>


<div class="col-sm-6 offset-sm-3 default-div">
    <h4><a href="{% url 'file_show' file.pk %}">{{ file.name }}</a></h4>
    <p>namespace: {{ file.raw_ns }}</p>
</div>


<div class="col-sm-6 offset-sm-3 default-div">
    <form action="" method="POST" class="form jumbotron">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="submit" value="dodaj tag" class="btn btn-info">
    </form>
</div>

<div class="col-sm-6 offset-sm-3 default-div">
    {% if tags %}
    <ul>
    {% for tag in tags %}
        <li><a href="{% url 'tag_edit' tag.pk %}">{{ tag.name }}, typ: {{ tag.get_type_display }}</a></li>
    {% endfor %}
    </ul>
    <hr>
    {% endif %}
</div>


{% endblock content %}

JPK_app/templates/JPK_app/jpktag_edit.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-6 offset-sm-3 default-div">
    <h2 class="page-header">Tag</h2>
    <form action="" method="POST" class="form">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="submit" value="zapisz" class="btn btn-info">
        <input type="submit" name="submit" value="usuń" class="btn btn-danger">
    </form>
</div>
{% endblock content %}

JPK_app/templates/JPK_app/jpktag_show.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2 class="page-header">{{ obj.name }}</h2>
<p>typ: {{ obj.get_type_display }}</p>
<p>tabela: {{ obj.table }}</p>

{% endblock content %}

JPK_app/templates/JPK_app/login.html
{% extends './_base.html' %}
{% load crispy_forms_tags %}

{% block nav %}
{% endblock nav %}

{% block content %}

<div class="col-md-12 col-lg-8 offset-lg-2">
    <div>
        <h2 class="page-header">Zaloguj się</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" name="submit" value="login" class="btn btn-info">
        </form>
    </div>
</div>

{% endblock content %}